baseURL: ''
languageCode: en-us
theme: SimpleIntro
title: Home
publishDir: public
params:
  mainText: Keep scrolling to peruse my projects.
  mainTitle: Hi, I'm Sara
  mainbg: https://picsum.photos/1920/1080
  name: Sara
menus: {}
menu:
  main:
    - identifier: about
      name: About
      url: '#about'
    - identifier: skills
      name: Skills
      url: '#skills'
    - identifier: projects
      name: Projects
      url: '#projects'
