baseURL: ''
languageCode: en-us
theme: SimpleIntro
title: Home
publishDir: public
params:
  mainText: Doctoral Student, Psychology Researcher, Statistics Enthusiast
  mainTitle: Sara Lieber
  mainbg: https://picsum.photos/1920/1080
  name: Sara
menus: {}
menu:
  main:
    - identifier: about
      name: About
      url: '#about'
    - identifier: CV
      name: CV
      url: 'https://github.com/sluopsy/website2/raw/master/themes/SimpleIntro/static/Lieber%20-%20CV.pdf'
    - identifier: skills
      name: Skills
      url: '#skills'
    - identifier: projects
      name: Projects
      url: '#projects'
    - identifier: Publications
      name: Publications
      url: '#publications'
